// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jbilling/purchaseorder/JBillingPurchaseOrderSyncEvent.proto

package com.appdirect.jbilling.event.purchaseorder;

public interface JBillingPurchaseOrderSyncEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.jbilling.event.purchaseorder.JBillingPurchaseOrderSyncEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 external_order_id = 1;</code>
   */
  long getExternalOrderId();

  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>repeated .com.appdirect.jbilling.event.purchaseorder.OrderLine order_lines = 3;</code>
   */
  java.util.List<com.appdirect.jbilling.event.purchaseorder.OrderLine> 
      getOrderLinesList();
  /**
   * <code>repeated .com.appdirect.jbilling.event.purchaseorder.OrderLine order_lines = 3;</code>
   */
  com.appdirect.jbilling.event.purchaseorder.OrderLine getOrderLines(int index);
  /**
   * <code>repeated .com.appdirect.jbilling.event.purchaseorder.OrderLine order_lines = 3;</code>
   */
  int getOrderLinesCount();
  /**
   * <code>repeated .com.appdirect.jbilling.event.purchaseorder.OrderLine order_lines = 3;</code>
   */
  java.util.List<? extends com.appdirect.jbilling.event.purchaseorder.OrderLineOrBuilder> 
      getOrderLinesOrBuilderList();
  /**
   * <code>repeated .com.appdirect.jbilling.event.purchaseorder.OrderLine order_lines = 3;</code>
   */
  com.appdirect.jbilling.event.purchaseorder.OrderLineOrBuilder getOrderLinesOrBuilder(
      int index);

  /**
   * <code>optional .google.protobuf.StringValue retryUuid = 4;</code>
   */
  boolean hasRetryUuid();
  /**
   * <code>optional .google.protobuf.StringValue retryUuid = 4;</code>
   */
  com.google.protobuf.StringValue getRetryUuid();
  /**
   * <code>optional .google.protobuf.StringValue retryUuid = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getRetryUuidOrBuilder();

  /**
   * <code>optional .google.protobuf.Int64Value companyEntitlementId = 5;</code>
   */
  boolean hasCompanyEntitlementId();
  /**
   * <code>optional .google.protobuf.Int64Value companyEntitlementId = 5;</code>
   */
  com.google.protobuf.Int64Value getCompanyEntitlementId();
  /**
   * <code>optional .google.protobuf.Int64Value companyEntitlementId = 5;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getCompanyEntitlementIdOrBuilder();
}
