// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jbilling/invoice/invoice.sync.proto

package com.appdirect.jbilling.event.invoice;

public interface InvoiceSyncOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.jbilling.event.invoice.InvoiceSync)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string bro_invoice_number_to_set = 2;</code>
   */
  java.lang.String getBroInvoiceNumberToSet();
  /**
   * <code>optional string bro_invoice_number_to_set = 2;</code>
   */
  com.google.protobuf.ByteString
      getBroInvoiceNumberToSetBytes();

  /**
   * <code>optional string bro_invoice_number_prefix_to_set = 3;</code>
   */
  java.lang.String getBroInvoiceNumberPrefixToSet();
  /**
   * <code>optional string bro_invoice_number_prefix_to_set = 3;</code>
   */
  com.google.protobuf.ByteString
      getBroInvoiceNumberPrefixToSetBytes();

  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Invoice invoice = 4;</code>
   */
  boolean hasInvoice();
  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Invoice invoice = 4;</code>
   */
  com.appdirect.jbilling.event.invoice.Invoice getInvoice();
  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Invoice invoice = 4;</code>
   */
  com.appdirect.jbilling.event.invoice.InvoiceOrBuilder getInvoiceOrBuilder();
}
