// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jbilling/invoice/void.event.proto

package com.appdirect.jbilling.event.invoice;

public interface JBillingInvoiceVoidEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.jbilling.event.invoice.JBillingInvoiceVoidEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Void void = 1;</code>
   */
  boolean hasVoid();
  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Void void = 1;</code>
   */
  com.appdirect.jbilling.event.invoice.Void getVoid();
  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Void void = 1;</code>
   */
  com.appdirect.jbilling.event.invoice.VoidOrBuilder getVoidOrBuilder();
}
