// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jbilling/invoice/operation.event.proto

package com.appdirect.jbilling.event.invoice;

public interface JBillingInvoiceOperationEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.jbilling.event.invoice.JBillingInvoiceOperationEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Operation operation = 1;</code>
   */
  boolean hasOperation();
  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Operation operation = 1;</code>
   */
  com.appdirect.jbilling.event.invoice.Operation getOperation();
  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Operation operation = 1;</code>
   */
  com.appdirect.jbilling.event.invoice.OperationOrBuilder getOperationOrBuilder();
}
