// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jbilling/invoice/void.proto

package com.appdirect.jbilling.event.invoice;

public interface VoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.jbilling.event.invoice.Void)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>optional string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>optional string timestamp = 3;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>optional string timestamp = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>optional bool success = 4;</code>
   */
  boolean getSuccess();

  /**
   * <code>optional string invoice_number = 5;</code>
   */
  java.lang.String getInvoiceNumber();
  /**
   * <code>optional string invoice_number = 5;</code>
   */
  com.google.protobuf.ByteString
      getInvoiceNumberBytes();

  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Invoice invoice = 6;</code>
   */
  boolean hasInvoice();
  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Invoice invoice = 6;</code>
   */
  com.appdirect.jbilling.event.invoice.Invoice getInvoice();
  /**
   * <code>optional .com.appdirect.jbilling.event.invoice.Invoice invoice = 6;</code>
   */
  com.appdirect.jbilling.event.invoice.InvoiceOrBuilder getInvoiceOrBuilder();
}
