// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jbilling/payment/payment.proto

package com.appdirect.jbilling.event.payment;

public interface PaymentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.jbilling.event.payment.Payment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 number = 1;</code>
   */
  int getNumber();

  /**
   * <code>optional int64 version = 2;</code>
   */
  long getVersion();

  /**
   * <code>optional string source = 3;</code>
   */
  java.lang.String getSource();
  /**
   * <code>optional string source = 3;</code>
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>optional int32 userId = 4;</code>
   */
  int getUserId();

  /**
   * <code>repeated int32 invoice_ids = 5;</code>
   */
  java.util.List<java.lang.Integer> getInvoiceIdsList();
  /**
   * <code>repeated int32 invoice_ids = 5;</code>
   */
  int getInvoiceIdsCount();
  /**
   * <code>repeated int32 invoice_ids = 5;</code>
   */
  int getInvoiceIds(int index);

  /**
   * <code>optional bool is_refund = 6;</code>
   */
  boolean getIsRefund();

  /**
   * <code>optional .google.protobuf.Int32Value refunded_payment_number = 7;</code>
   */
  boolean hasRefundedPaymentNumber();
  /**
   * <code>optional .google.protobuf.Int32Value refunded_payment_number = 7;</code>
   */
  com.google.protobuf.Int32Value getRefundedPaymentNumber();
  /**
   * <code>optional .google.protobuf.Int32Value refunded_payment_number = 7;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getRefundedPaymentNumberOrBuilder();

  /**
   * <code>optional string payment_date = 8;</code>
   */
  java.lang.String getPaymentDate();
  /**
   * <code>optional string payment_date = 8;</code>
   */
  com.google.protobuf.ByteString
      getPaymentDateBytes();

  /**
   * <code>optional string result = 9;</code>
   */
  java.lang.String getResult();
  /**
   * <code>optional string result = 9;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>optional string currency = 10;</code>
   */
  java.lang.String getCurrency();
  /**
   * <code>optional string currency = 10;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>optional string amount = 11;</code>
   */
  java.lang.String getAmount();
  /**
   * <code>optional string amount = 11;</code>
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>repeated .com.appdirect.jbilling.event.MetaField meta_fields = 12;</code>
   */
  java.util.List<com.appdirect.jbilling.event.MetaField> 
      getMetaFieldsList();
  /**
   * <code>repeated .com.appdirect.jbilling.event.MetaField meta_fields = 12;</code>
   */
  com.appdirect.jbilling.event.MetaField getMetaFields(int index);
  /**
   * <code>repeated .com.appdirect.jbilling.event.MetaField meta_fields = 12;</code>
   */
  int getMetaFieldsCount();
  /**
   * <code>repeated .com.appdirect.jbilling.event.MetaField meta_fields = 12;</code>
   */
  java.util.List<? extends com.appdirect.jbilling.event.MetaFieldOrBuilder> 
      getMetaFieldsOrBuilderList();
  /**
   * <code>repeated .com.appdirect.jbilling.event.MetaField meta_fields = 12;</code>
   */
  com.appdirect.jbilling.event.MetaFieldOrBuilder getMetaFieldsOrBuilder(
      int index);

  /**
   * <code>optional .com.appdirect.jbilling.event.payment.Authorization authorization = 13;</code>
   */
  boolean hasAuthorization();
  /**
   * <code>optional .com.appdirect.jbilling.event.payment.Authorization authorization = 13;</code>
   */
  com.appdirect.jbilling.event.payment.Authorization getAuthorization();
  /**
   * <code>optional .com.appdirect.jbilling.event.payment.Authorization authorization = 13;</code>
   */
  com.appdirect.jbilling.event.payment.AuthorizationOrBuilder getAuthorizationOrBuilder();

  /**
   * <code>optional string payment_method = 14;</code>
   */
  java.lang.String getPaymentMethod();
  /**
   * <code>optional string payment_method = 14;</code>
   */
  com.google.protobuf.ByteString
      getPaymentMethodBytes();

  /**
   * <code>optional string balance = 15;</code>
   */
  java.lang.String getBalance();
  /**
   * <code>optional string balance = 15;</code>
   */
  com.google.protobuf.ByteString
      getBalanceBytes();

  /**
   * <code>optional bool deleted = 16;</code>
   */
  boolean getDeleted();

  /**
   * <code>optional string notes = 17;</code>
   */
  java.lang.String getNotes();
  /**
   * <code>optional string notes = 17;</code>
   */
  com.google.protobuf.ByteString
      getNotesBytes();

  /**
   * <code>map&lt;string, string&gt; extra_information = 18;</code>
   */
  int getExtraInformationCount();
  /**
   * <code>map&lt;string, string&gt; extra_information = 18;</code>
   */
  boolean containsExtraInformation(
      java.lang.String key);
  /**
   * Use {@link #getExtraInformationMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtraInformation();
  /**
   * <code>map&lt;string, string&gt; extra_information = 18;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtraInformationMap();
  /**
   * <code>map&lt;string, string&gt; extra_information = 18;</code>
   */

  java.lang.String getExtraInformationOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; extra_information = 18;</code>
   */

  java.lang.String getExtraInformationOrThrow(
      java.lang.String key);

  /**
   * <code>optional string refunded_invoice_id = 19;</code>
   */
  java.lang.String getRefundedInvoiceId();
  /**
   * <code>optional string refunded_invoice_id = 19;</code>
   */
  com.google.protobuf.ByteString
      getRefundedInvoiceIdBytes();
}
