// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: application.proto

package com.appdirect.event;

public interface ApplicationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.Application)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  boolean hasResource();
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  com.appdirect.event.Resource getResource();
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  com.appdirect.event.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated string tags = 4;</code>
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 4;</code>
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 4;</code>
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <code>optional string url = 5;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>optional string url = 5;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>optional int64 lastModified = 6;</code>
   */
  long getLastModified();

  /**
   * <code>optional string productType = 7;</code>
   */
  java.lang.String getProductType();
  /**
   * <code>optional string productType = 7;</code>
   */
  com.google.protobuf.ByteString
      getProductTypeBytes();

  /**
   * <code>optional string imageUrl = 8;</code>
   */
  java.lang.String getImageUrl();
  /**
   * <code>optional string imageUrl = 8;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();
}
