// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assignment.proto

package com.appdirect.event;

public interface AssignmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.Assignment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  boolean hasResource();
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  com.appdirect.event.Resource getResource();
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  com.appdirect.event.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <code>optional int64 creationDate = 2;</code>
   */
  long getCreationDate();

  /**
   * <code>optional string externalAccountId = 3;</code>
   */
  java.lang.String getExternalAccountId();
  /**
   * <code>optional string externalAccountId = 3;</code>
   */
  com.google.protobuf.ByteString
      getExternalAccountIdBytes();

  /**
   * <code>optional string status = 4;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>optional string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>optional string userUuid = 5;</code>
   */
  java.lang.String getUserUuid();
  /**
   * <code>optional string userUuid = 5;</code>
   */
  com.google.protobuf.ByteString
      getUserUuidBytes();

  /**
   * <code>optional .com.appdirect.event.Subscription subscription = 6;</code>
   */
  boolean hasSubscription();
  /**
   * <code>optional .com.appdirect.event.Subscription subscription = 6;</code>
   */
  com.appdirect.event.Subscription getSubscription();
  /**
   * <code>optional .com.appdirect.event.Subscription subscription = 6;</code>
   */
  com.appdirect.event.SubscriptionOrBuilder getSubscriptionOrBuilder();
}
