// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attribute.event.proto

package com.appdirect.event;

public interface AttributeCreatedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.AttributeCreated)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.Attribute attribute = 1;</code>
   */
  boolean hasAttribute();
  /**
   * <code>optional .com.appdirect.event.Attribute attribute = 1;</code>
   */
  com.appdirect.event.Attribute getAttribute();
  /**
   * <code>optional .com.appdirect.event.Attribute attribute = 1;</code>
   */
  com.appdirect.event.AttributeOrBuilder getAttributeOrBuilder();

  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 2;</code>
   */
  boolean hasMetadata();
  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 2;</code>
   */
  com.appdirect.event.Metadata getMetadata();
  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 2;</code>
   */
  com.appdirect.event.MetadataOrBuilder getMetadataOrBuilder();
}
