// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.event.proto

package com.appdirect.event;

public final class ChannelEvent {
  private ChannelEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_ChannelUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_ChannelUpdated_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023channel.event.proto\022\023com.appdirect.eve" +
      "nt\032\rchannel.proto\032\016metadata.proto\"p\n\016Cha" +
      "nnelUpdated\022-\n\007channel\030\001 \001(\0132\034.com.appdi" +
      "rect.event.Channel\022/\n\010metadata\030\002 \001(\0132\035.c" +
      "om.appdirect.event.MetadataB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.appdirect.event.ChannelOuterClass.getDescriptor(),
          com.appdirect.event.MetadataOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_appdirect_event_ChannelUpdated_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appdirect_event_ChannelUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_ChannelUpdated_descriptor,
        new java.lang.String[] { "Channel", "Metadata", });
    com.appdirect.event.ChannelOuterClass.getDescriptor();
    com.appdirect.event.MetadataOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
