// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

package com.appdirect.event;

public final class ChannelOuterClass {
  private ChannelOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_Channel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_Channel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_Setting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_Setting_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rchannel.proto\022\023com.appdirect.event\032\016re" +
      "source.proto\"j\n\007Channel\022/\n\010resource\030\001 \001(" +
      "\0132\035.com.appdirect.event.Resource\022.\n\010sett" +
      "ings\030\002 \003(\0132\034.com.appdirect.event.Setting" +
      "\"\274\001\n\007Setting\022\014\n\004name\030\001 \001(\t\022\020\n\010oldValue\030\002" +
      " \001(\t\022\020\n\010newValue\030\003 \001(\t\022/\n\004type\030\004 \001(\0162!.c" +
      "om.appdirect.event.Setting.Type\"N\n\004Type\022" +
      "\n\n\006OBJECT\020\000\022\n\n\006STRING\020\001\022\013\n\007INTEGER\020\002\022\010\n\004" +
      "LONG\020\003\022\013\n\007BOOLEAN\020\004\022\n\n\006DOUBLE\020\005B\002P\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.appdirect.event.ResourceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_appdirect_event_Channel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appdirect_event_Channel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_Channel_descriptor,
        new java.lang.String[] { "Resource", "Settings", });
    internal_static_com_appdirect_event_Setting_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_appdirect_event_Setting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_Setting_descriptor,
        new java.lang.String[] { "Name", "OldValue", "NewValue", "Type", });
    com.appdirect.event.ResourceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
