// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customAttribute.event.proto

package com.appdirect.event;

public interface CustomAttributeCreatedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.CustomAttributeCreated)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.CustomAttribute customAttribute = 1;</code>
   */
  boolean hasCustomAttribute();
  /**
   * <code>optional .com.appdirect.event.CustomAttribute customAttribute = 1;</code>
   */
  com.appdirect.event.CustomAttribute getCustomAttribute();
  /**
   * <code>optional .com.appdirect.event.CustomAttribute customAttribute = 1;</code>
   */
  com.appdirect.event.CustomAttributeOrBuilder getCustomAttributeOrBuilder();
}
