// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customAttribute.proto

package com.appdirect.event;

/**
 * Protobuf type {@code com.appdirect.event.CustomAttribute}
 */
public  final class CustomAttribute extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.appdirect.event.CustomAttribute)
    CustomAttributeOrBuilder {
  // Use CustomAttribute.newBuilder() to construct.
  private CustomAttribute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CustomAttribute() {
    key_ = "";
    companyUUID_ = "";
    entityType_ = 0;
    partner_ = "";
    system_ = false;
    attributeType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CustomAttribute(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.appdirect.event.Resource.Builder subBuilder = null;
            if (resource_ != null) {
              subBuilder = resource_.toBuilder();
            }
            resource_ = input.readMessage(com.appdirect.event.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resource_);
              resource_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              label_ = com.google.protobuf.MapField.newMapField(
                  LabelDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            label__ = input.readMessage(
                LabelDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            label_.getMutableMap().put(
                label__.getKey(), label__.getValue());
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              hint_ = com.google.protobuf.MapField.newMapField(
                  HintDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            hint__ = input.readMessage(
                HintDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            hint_.getMutableMap().put(
                hint__.getKey(), hint__.getValue());
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            companyUUID_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            entityType_ = rawValue;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            partner_ = s;
            break;
          }
          case 64: {

            system_ = input.readBool();
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            attributeType_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.appdirect.event.CustomAttributeOuterClass.internal_static_com_appdirect_event_CustomAttribute_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetLabel();
      case 4:
        return internalGetHint();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.appdirect.event.CustomAttributeOuterClass.internal_static_com_appdirect_event_CustomAttribute_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.appdirect.event.CustomAttribute.class, com.appdirect.event.CustomAttribute.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_FIELD_NUMBER = 1;
  private com.appdirect.event.Resource resource_;
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  public boolean hasResource() {
    return resource_ != null;
  }
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  public com.appdirect.event.Resource getResource() {
    return resource_ == null ? com.appdirect.event.Resource.getDefaultInstance() : resource_;
  }
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  public com.appdirect.event.ResourceOrBuilder getResourceOrBuilder() {
    return getResource();
  }

  public static final int KEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object key_;
  /**
   * <code>optional string key = 2;</code>
   */
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>optional string key = 2;</code>
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABEL_FIELD_NUMBER = 3;
  private static final class LabelDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.appdirect.event.CustomAttributeOuterClass.internal_static_com_appdirect_event_CustomAttribute_LabelEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> label_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetLabel() {
    if (label_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          LabelDefaultEntryHolder.defaultEntry);
    }
    return label_;
  }

  public int getLabelCount() {
    return internalGetLabel().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; label = 3;</code>
   */

  public boolean containsLabel(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetLabel().getMap().containsKey(key);
  }
  /**
   * Use {@link #getLabelMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getLabel() {
    return getLabelMap();
  }
  /**
   * <code>map&lt;string, string&gt; label = 3;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getLabelMap() {
    return internalGetLabel().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; label = 3;</code>
   */

  public java.lang.String getLabelOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetLabel().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; label = 3;</code>
   */

  public java.lang.String getLabelOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetLabel().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int HINT_FIELD_NUMBER = 4;
  private static final class HintDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.appdirect.event.CustomAttributeOuterClass.internal_static_com_appdirect_event_CustomAttribute_HintEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> hint_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetHint() {
    if (hint_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          HintDefaultEntryHolder.defaultEntry);
    }
    return hint_;
  }

  public int getHintCount() {
    return internalGetHint().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; hint = 4;</code>
   */

  public boolean containsHint(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetHint().getMap().containsKey(key);
  }
  /**
   * Use {@link #getHintMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getHint() {
    return getHintMap();
  }
  /**
   * <code>map&lt;string, string&gt; hint = 4;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getHintMap() {
    return internalGetHint().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; hint = 4;</code>
   */

  public java.lang.String getHintOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHint().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; hint = 4;</code>
   */

  public java.lang.String getHintOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHint().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int COMPANYUUID_FIELD_NUMBER = 5;
  private volatile java.lang.Object companyUUID_;
  /**
   * <code>optional string companyUUID = 5;</code>
   */
  public java.lang.String getCompanyUUID() {
    java.lang.Object ref = companyUUID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyUUID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string companyUUID = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCompanyUUIDBytes() {
    java.lang.Object ref = companyUUID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyUUID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTITYTYPE_FIELD_NUMBER = 6;
  private int entityType_;
  /**
   * <code>optional .com.appdirect.event.EntityType entityType = 6;</code>
   */
  public int getEntityTypeValue() {
    return entityType_;
  }
  /**
   * <code>optional .com.appdirect.event.EntityType entityType = 6;</code>
   */
  public com.appdirect.event.EntityType getEntityType() {
    com.appdirect.event.EntityType result = com.appdirect.event.EntityType.valueOf(entityType_);
    return result == null ? com.appdirect.event.EntityType.UNRECOGNIZED : result;
  }

  public static final int PARTNER_FIELD_NUMBER = 7;
  private volatile java.lang.Object partner_;
  /**
   * <code>optional string partner = 7;</code>
   */
  public java.lang.String getPartner() {
    java.lang.Object ref = partner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partner_ = s;
      return s;
    }
  }
  /**
   * <code>optional string partner = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPartnerBytes() {
    java.lang.Object ref = partner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSTEM_FIELD_NUMBER = 8;
  private boolean system_;
  /**
   * <code>optional bool system = 8;</code>
   */
  public boolean getSystem() {
    return system_;
  }

  public static final int ATTRIBUTETYPE_FIELD_NUMBER = 9;
  private int attributeType_;
  /**
   * <code>optional .com.appdirect.event.AttributeType attributeType = 9;</code>
   */
  public int getAttributeTypeValue() {
    return attributeType_;
  }
  /**
   * <code>optional .com.appdirect.event.AttributeType attributeType = 9;</code>
   */
  public com.appdirect.event.AttributeType getAttributeType() {
    com.appdirect.event.AttributeType result = com.appdirect.event.AttributeType.valueOf(attributeType_);
    return result == null ? com.appdirect.event.AttributeType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resource_ != null) {
      output.writeMessage(1, getResource());
    }
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetLabel(),
        LabelDefaultEntryHolder.defaultEntry,
        3);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetHint(),
        HintDefaultEntryHolder.defaultEntry,
        4);
    if (!getCompanyUUIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, companyUUID_);
    }
    if (entityType_ != com.appdirect.event.EntityType.COMPANY.getNumber()) {
      output.writeEnum(6, entityType_);
    }
    if (!getPartnerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, partner_);
    }
    if (system_ != false) {
      output.writeBool(8, system_);
    }
    if (attributeType_ != com.appdirect.event.AttributeType.TEXT.getNumber()) {
      output.writeEnum(9, attributeType_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetLabel().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      label__ = LabelDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, label__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetHint().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      hint__ = HintDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, hint__);
    }
    if (!getCompanyUUIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, companyUUID_);
    }
    if (entityType_ != com.appdirect.event.EntityType.COMPANY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, entityType_);
    }
    if (!getPartnerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, partner_);
    }
    if (system_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, system_);
    }
    if (attributeType_ != com.appdirect.event.AttributeType.TEXT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, attributeType_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.appdirect.event.CustomAttribute)) {
      return super.equals(obj);
    }
    com.appdirect.event.CustomAttribute other = (com.appdirect.event.CustomAttribute) obj;

    boolean result = true;
    result = result && (hasResource() == other.hasResource());
    if (hasResource()) {
      result = result && getResource()
          .equals(other.getResource());
    }
    result = result && getKey()
        .equals(other.getKey());
    result = result && internalGetLabel().equals(
        other.internalGetLabel());
    result = result && internalGetHint().equals(
        other.internalGetHint());
    result = result && getCompanyUUID()
        .equals(other.getCompanyUUID());
    result = result && entityType_ == other.entityType_;
    result = result && getPartner()
        .equals(other.getPartner());
    result = result && (getSystem()
        == other.getSystem());
    result = result && attributeType_ == other.attributeType_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (!internalGetLabel().getMap().isEmpty()) {
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + internalGetLabel().hashCode();
    }
    if (!internalGetHint().getMap().isEmpty()) {
      hash = (37 * hash) + HINT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetHint().hashCode();
    }
    hash = (37 * hash) + COMPANYUUID_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyUUID().hashCode();
    hash = (37 * hash) + ENTITYTYPE_FIELD_NUMBER;
    hash = (53 * hash) + entityType_;
    hash = (37 * hash) + PARTNER_FIELD_NUMBER;
    hash = (53 * hash) + getPartner().hashCode();
    hash = (37 * hash) + SYSTEM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSystem());
    hash = (37 * hash) + ATTRIBUTETYPE_FIELD_NUMBER;
    hash = (53 * hash) + attributeType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.appdirect.event.CustomAttribute parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appdirect.event.CustomAttribute parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appdirect.event.CustomAttribute parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appdirect.event.CustomAttribute parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appdirect.event.CustomAttribute parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appdirect.event.CustomAttribute parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appdirect.event.CustomAttribute parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.appdirect.event.CustomAttribute parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appdirect.event.CustomAttribute parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appdirect.event.CustomAttribute parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.appdirect.event.CustomAttribute prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.appdirect.event.CustomAttribute}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.appdirect.event.CustomAttribute)
      com.appdirect.event.CustomAttributeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appdirect.event.CustomAttributeOuterClass.internal_static_com_appdirect_event_CustomAttribute_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetLabel();
        case 4:
          return internalGetHint();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableLabel();
        case 4:
          return internalGetMutableHint();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appdirect.event.CustomAttributeOuterClass.internal_static_com_appdirect_event_CustomAttribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.appdirect.event.CustomAttribute.class, com.appdirect.event.CustomAttribute.Builder.class);
    }

    // Construct using com.appdirect.event.CustomAttribute.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (resourceBuilder_ == null) {
        resource_ = null;
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }
      key_ = "";

      internalGetMutableLabel().clear();
      internalGetMutableHint().clear();
      companyUUID_ = "";

      entityType_ = 0;

      partner_ = "";

      system_ = false;

      attributeType_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.appdirect.event.CustomAttributeOuterClass.internal_static_com_appdirect_event_CustomAttribute_descriptor;
    }

    public com.appdirect.event.CustomAttribute getDefaultInstanceForType() {
      return com.appdirect.event.CustomAttribute.getDefaultInstance();
    }

    public com.appdirect.event.CustomAttribute build() {
      com.appdirect.event.CustomAttribute result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.appdirect.event.CustomAttribute buildPartial() {
      com.appdirect.event.CustomAttribute result = new com.appdirect.event.CustomAttribute(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (resourceBuilder_ == null) {
        result.resource_ = resource_;
      } else {
        result.resource_ = resourceBuilder_.build();
      }
      result.key_ = key_;
      result.label_ = internalGetLabel();
      result.label_.makeImmutable();
      result.hint_ = internalGetHint();
      result.hint_.makeImmutable();
      result.companyUUID_ = companyUUID_;
      result.entityType_ = entityType_;
      result.partner_ = partner_;
      result.system_ = system_;
      result.attributeType_ = attributeType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.appdirect.event.CustomAttribute) {
        return mergeFrom((com.appdirect.event.CustomAttribute)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.appdirect.event.CustomAttribute other) {
      if (other == com.appdirect.event.CustomAttribute.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      internalGetMutableLabel().mergeFrom(
          other.internalGetLabel());
      internalGetMutableHint().mergeFrom(
          other.internalGetHint());
      if (!other.getCompanyUUID().isEmpty()) {
        companyUUID_ = other.companyUUID_;
        onChanged();
      }
      if (other.entityType_ != 0) {
        setEntityTypeValue(other.getEntityTypeValue());
      }
      if (!other.getPartner().isEmpty()) {
        partner_ = other.partner_;
        onChanged();
      }
      if (other.getSystem() != false) {
        setSystem(other.getSystem());
      }
      if (other.attributeType_ != 0) {
        setAttributeTypeValue(other.getAttributeTypeValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.appdirect.event.CustomAttribute parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.appdirect.event.CustomAttribute) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.appdirect.event.Resource resource_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.appdirect.event.Resource, com.appdirect.event.Resource.Builder, com.appdirect.event.ResourceOrBuilder> resourceBuilder_;
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public boolean hasResource() {
      return resourceBuilder_ != null || resource_ != null;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public com.appdirect.event.Resource getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? com.appdirect.event.Resource.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder setResource(com.appdirect.event.Resource value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        resourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder setResource(
        com.appdirect.event.Resource.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder mergeResource(com.appdirect.event.Resource value) {
      if (resourceBuilder_ == null) {
        if (resource_ != null) {
          resource_ =
            com.appdirect.event.Resource.newBuilder(resource_).mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        resourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder clearResource() {
      if (resourceBuilder_ == null) {
        resource_ = null;
        onChanged();
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public com.appdirect.event.Resource.Builder getResourceBuilder() {
      
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public com.appdirect.event.ResourceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            com.appdirect.event.Resource.getDefaultInstance() : resource_;
      }
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.appdirect.event.Resource, com.appdirect.event.Resource.Builder, com.appdirect.event.ResourceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.appdirect.event.Resource, com.appdirect.event.Resource.Builder, com.appdirect.event.ResourceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>optional string key = 2;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string key = 2;</code>
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string key = 2;</code>
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>optional string key = 2;</code>
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> label_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetLabel() {
      if (label_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LabelDefaultEntryHolder.defaultEntry);
      }
      return label_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableLabel() {
      onChanged();;
      if (label_ == null) {
        label_ = com.google.protobuf.MapField.newMapField(
            LabelDefaultEntryHolder.defaultEntry);
      }
      if (!label_.isMutable()) {
        label_ = label_.copy();
      }
      return label_;
    }

    public int getLabelCount() {
      return internalGetLabel().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; label = 3;</code>
     */

    public boolean containsLabel(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetLabel().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLabelMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getLabel() {
      return getLabelMap();
    }
    /**
     * <code>map&lt;string, string&gt; label = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getLabelMap() {
      return internalGetLabel().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; label = 3;</code>
     */

    public java.lang.String getLabelOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLabel().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; label = 3;</code>
     */

    public java.lang.String getLabelOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLabel().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearLabel() {
      getMutableLabel().clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; label = 3;</code>
     */

    public Builder removeLabel(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      getMutableLabel().remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableLabel() {
      return internalGetMutableLabel().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; label = 3;</code>
     */
    public Builder putLabel(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      getMutableLabel().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; label = 3;</code>
     */

    public Builder putAllLabel(
        java.util.Map<java.lang.String, java.lang.String> values) {
      getMutableLabel().putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> hint_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetHint() {
      if (hint_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HintDefaultEntryHolder.defaultEntry);
      }
      return hint_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableHint() {
      onChanged();;
      if (hint_ == null) {
        hint_ = com.google.protobuf.MapField.newMapField(
            HintDefaultEntryHolder.defaultEntry);
      }
      if (!hint_.isMutable()) {
        hint_ = hint_.copy();
      }
      return hint_;
    }

    public int getHintCount() {
      return internalGetHint().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; hint = 4;</code>
     */

    public boolean containsHint(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetHint().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHintMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHint() {
      return getHintMap();
    }
    /**
     * <code>map&lt;string, string&gt; hint = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getHintMap() {
      return internalGetHint().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; hint = 4;</code>
     */

    public java.lang.String getHintOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHint().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; hint = 4;</code>
     */

    public java.lang.String getHintOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHint().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearHint() {
      getMutableHint().clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; hint = 4;</code>
     */

    public Builder removeHint(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      getMutableHint().remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableHint() {
      return internalGetMutableHint().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; hint = 4;</code>
     */
    public Builder putHint(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      getMutableHint().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; hint = 4;</code>
     */

    public Builder putAllHint(
        java.util.Map<java.lang.String, java.lang.String> values) {
      getMutableHint().putAll(values);
      return this;
    }

    private java.lang.Object companyUUID_ = "";
    /**
     * <code>optional string companyUUID = 5;</code>
     */
    public java.lang.String getCompanyUUID() {
      java.lang.Object ref = companyUUID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyUUID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string companyUUID = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyUUIDBytes() {
      java.lang.Object ref = companyUUID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string companyUUID = 5;</code>
     */
    public Builder setCompanyUUID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyUUID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string companyUUID = 5;</code>
     */
    public Builder clearCompanyUUID() {
      
      companyUUID_ = getDefaultInstance().getCompanyUUID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string companyUUID = 5;</code>
     */
    public Builder setCompanyUUIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyUUID_ = value;
      onChanged();
      return this;
    }

    private int entityType_ = 0;
    /**
     * <code>optional .com.appdirect.event.EntityType entityType = 6;</code>
     */
    public int getEntityTypeValue() {
      return entityType_;
    }
    /**
     * <code>optional .com.appdirect.event.EntityType entityType = 6;</code>
     */
    public Builder setEntityTypeValue(int value) {
      entityType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.appdirect.event.EntityType entityType = 6;</code>
     */
    public com.appdirect.event.EntityType getEntityType() {
      com.appdirect.event.EntityType result = com.appdirect.event.EntityType.valueOf(entityType_);
      return result == null ? com.appdirect.event.EntityType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.appdirect.event.EntityType entityType = 6;</code>
     */
    public Builder setEntityType(com.appdirect.event.EntityType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      entityType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.appdirect.event.EntityType entityType = 6;</code>
     */
    public Builder clearEntityType() {
      
      entityType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object partner_ = "";
    /**
     * <code>optional string partner = 7;</code>
     */
    public java.lang.String getPartner() {
      java.lang.Object ref = partner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string partner = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPartnerBytes() {
      java.lang.Object ref = partner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string partner = 7;</code>
     */
    public Builder setPartner(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partner_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string partner = 7;</code>
     */
    public Builder clearPartner() {
      
      partner_ = getDefaultInstance().getPartner();
      onChanged();
      return this;
    }
    /**
     * <code>optional string partner = 7;</code>
     */
    public Builder setPartnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partner_ = value;
      onChanged();
      return this;
    }

    private boolean system_ ;
    /**
     * <code>optional bool system = 8;</code>
     */
    public boolean getSystem() {
      return system_;
    }
    /**
     * <code>optional bool system = 8;</code>
     */
    public Builder setSystem(boolean value) {
      
      system_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool system = 8;</code>
     */
    public Builder clearSystem() {
      
      system_ = false;
      onChanged();
      return this;
    }

    private int attributeType_ = 0;
    /**
     * <code>optional .com.appdirect.event.AttributeType attributeType = 9;</code>
     */
    public int getAttributeTypeValue() {
      return attributeType_;
    }
    /**
     * <code>optional .com.appdirect.event.AttributeType attributeType = 9;</code>
     */
    public Builder setAttributeTypeValue(int value) {
      attributeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.appdirect.event.AttributeType attributeType = 9;</code>
     */
    public com.appdirect.event.AttributeType getAttributeType() {
      com.appdirect.event.AttributeType result = com.appdirect.event.AttributeType.valueOf(attributeType_);
      return result == null ? com.appdirect.event.AttributeType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .com.appdirect.event.AttributeType attributeType = 9;</code>
     */
    public Builder setAttributeType(com.appdirect.event.AttributeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      attributeType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.appdirect.event.AttributeType attributeType = 9;</code>
     */
    public Builder clearAttributeType() {
      
      attributeType_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.appdirect.event.CustomAttribute)
  }

  // @@protoc_insertion_point(class_scope:com.appdirect.event.CustomAttribute)
  private static final com.appdirect.event.CustomAttribute DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.appdirect.event.CustomAttribute();
  }

  public static com.appdirect.event.CustomAttribute getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CustomAttribute>
      PARSER = new com.google.protobuf.AbstractParser<CustomAttribute>() {
    public CustomAttribute parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomAttribute(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CustomAttribute> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CustomAttribute> getParserForType() {
    return PARSER;
  }

  public com.appdirect.event.CustomAttribute getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

