// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataConnection.proto

package com.appdirect.event;

public final class DataConnectionOuterClass {
  private DataConnectionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_DataConnection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_DataConnection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024dataConnection.proto\022\023com.appdirect.ev" +
      "ent\032\016resource.proto\"\243\002\n\016DataConnection\022/" +
      "\n\010resource\030\001 \001(\0132\035.com.appdirect.event.R" +
      "esource\022\024\n\014connectionId\030\002 \001(\t\022\020\n\010eventUr" +
      "l\030\003 \001(\t\022\036\n\026companyEntitlementUuid\030\004 \001(\t\022" +
      "\020\n\010userUuid\030\005 \001(\t\022\033\n\023userEntitlementUuid" +
      "\030\006 \001(\t\022\r\n\005email\030\007 \001(\t\022\031\n\021accountIdentifi" +
      "er\030\010 \001(\t\022\027\n\017connectorStatus\030\t \001(\t\022\r\n\005sta" +
      "te\030\n \001(\t\022\027\n\017applicationUuid\030\013 \001(\tB\002P\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.appdirect.event.ResourceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_appdirect_event_DataConnection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appdirect_event_DataConnection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_DataConnection_descriptor,
        new java.lang.String[] { "Resource", "ConnectionId", "EventUrl", "CompanyEntitlementUuid", "UserUuid", "UserEntitlementUuid", "Email", "AccountIdentifier", "ConnectorStatus", "State", "ApplicationUuid", });
    com.appdirect.event.ResourceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
