// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gdprRequest.event.proto

package com.appdirect.event;

/**
 * Protobuf type {@code com.appdirect.event.GDPRRequest}
 */
public  final class GDPRRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.appdirect.event.GDPRRequest)
    GDPRRequestOrBuilder {
  // Use GDPRRequest.newBuilder() to construct.
  private GDPRRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GDPRRequest() {
    emailAddress_ = "";
    userID_ = 0L;
    userUuid_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GDPRRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            emailAddress_ = s;
            break;
          }
          case 16: {

            userID_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userUuid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.appdirect.event.GdprRequestEvent.internal_static_com_appdirect_event_GDPRRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.appdirect.event.GdprRequestEvent.internal_static_com_appdirect_event_GDPRRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.appdirect.event.GDPRRequest.class, com.appdirect.event.GDPRRequest.Builder.class);
  }

  public static final int EMAILADDRESS_FIELD_NUMBER = 1;
  private volatile java.lang.Object emailAddress_;
  /**
   * <code>optional string emailAddress = 1;</code>
   */
  public java.lang.String getEmailAddress() {
    java.lang.Object ref = emailAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      emailAddress_ = s;
      return s;
    }
  }
  /**
   * <code>optional string emailAddress = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEmailAddressBytes() {
    java.lang.Object ref = emailAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      emailAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 2;
  private long userID_;
  /**
   * <code>optional int64 userID = 2;</code>
   */
  public long getUserID() {
    return userID_;
  }

  public static final int USERUUID_FIELD_NUMBER = 3;
  private volatile java.lang.Object userUuid_;
  /**
   * <code>optional string userUuid = 3;</code>
   */
  public java.lang.String getUserUuid() {
    java.lang.Object ref = userUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userUuid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string userUuid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserUuidBytes() {
    java.lang.Object ref = userUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEmailAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, emailAddress_);
    }
    if (userID_ != 0L) {
      output.writeInt64(2, userID_);
    }
    if (!getUserUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userUuid_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEmailAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, emailAddress_);
    }
    if (userID_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, userID_);
    }
    if (!getUserUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userUuid_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.appdirect.event.GDPRRequest)) {
      return super.equals(obj);
    }
    com.appdirect.event.GDPRRequest other = (com.appdirect.event.GDPRRequest) obj;

    boolean result = true;
    result = result && getEmailAddress()
        .equals(other.getEmailAddress());
    result = result && (getUserID()
        == other.getUserID());
    result = result && getUserUuid()
        .equals(other.getUserUuid());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + EMAILADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getEmailAddress().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserID());
    hash = (37 * hash) + USERUUID_FIELD_NUMBER;
    hash = (53 * hash) + getUserUuid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.appdirect.event.GDPRRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appdirect.event.GDPRRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appdirect.event.GDPRRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appdirect.event.GDPRRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appdirect.event.GDPRRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appdirect.event.GDPRRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appdirect.event.GDPRRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.appdirect.event.GDPRRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appdirect.event.GDPRRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appdirect.event.GDPRRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.appdirect.event.GDPRRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.appdirect.event.GDPRRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.appdirect.event.GDPRRequest)
      com.appdirect.event.GDPRRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appdirect.event.GdprRequestEvent.internal_static_com_appdirect_event_GDPRRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appdirect.event.GdprRequestEvent.internal_static_com_appdirect_event_GDPRRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.appdirect.event.GDPRRequest.class, com.appdirect.event.GDPRRequest.Builder.class);
    }

    // Construct using com.appdirect.event.GDPRRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      emailAddress_ = "";

      userID_ = 0L;

      userUuid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.appdirect.event.GdprRequestEvent.internal_static_com_appdirect_event_GDPRRequest_descriptor;
    }

    public com.appdirect.event.GDPRRequest getDefaultInstanceForType() {
      return com.appdirect.event.GDPRRequest.getDefaultInstance();
    }

    public com.appdirect.event.GDPRRequest build() {
      com.appdirect.event.GDPRRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.appdirect.event.GDPRRequest buildPartial() {
      com.appdirect.event.GDPRRequest result = new com.appdirect.event.GDPRRequest(this);
      result.emailAddress_ = emailAddress_;
      result.userID_ = userID_;
      result.userUuid_ = userUuid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.appdirect.event.GDPRRequest) {
        return mergeFrom((com.appdirect.event.GDPRRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.appdirect.event.GDPRRequest other) {
      if (other == com.appdirect.event.GDPRRequest.getDefaultInstance()) return this;
      if (!other.getEmailAddress().isEmpty()) {
        emailAddress_ = other.emailAddress_;
        onChanged();
      }
      if (other.getUserID() != 0L) {
        setUserID(other.getUserID());
      }
      if (!other.getUserUuid().isEmpty()) {
        userUuid_ = other.userUuid_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.appdirect.event.GDPRRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.appdirect.event.GDPRRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object emailAddress_ = "";
    /**
     * <code>optional string emailAddress = 1;</code>
     */
    public java.lang.String getEmailAddress() {
      java.lang.Object ref = emailAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emailAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string emailAddress = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailAddressBytes() {
      java.lang.Object ref = emailAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emailAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string emailAddress = 1;</code>
     */
    public Builder setEmailAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emailAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string emailAddress = 1;</code>
     */
    public Builder clearEmailAddress() {
      
      emailAddress_ = getDefaultInstance().getEmailAddress();
      onChanged();
      return this;
    }
    /**
     * <code>optional string emailAddress = 1;</code>
     */
    public Builder setEmailAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emailAddress_ = value;
      onChanged();
      return this;
    }

    private long userID_ ;
    /**
     * <code>optional int64 userID = 2;</code>
     */
    public long getUserID() {
      return userID_;
    }
    /**
     * <code>optional int64 userID = 2;</code>
     */
    public Builder setUserID(long value) {
      
      userID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 userID = 2;</code>
     */
    public Builder clearUserID() {
      
      userID_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object userUuid_ = "";
    /**
     * <code>optional string userUuid = 3;</code>
     */
    public java.lang.String getUserUuid() {
      java.lang.Object ref = userUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string userUuid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserUuidBytes() {
      java.lang.Object ref = userUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userUuid = 3;</code>
     */
    public Builder setUserUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userUuid = 3;</code>
     */
    public Builder clearUserUuid() {
      
      userUuid_ = getDefaultInstance().getUserUuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string userUuid = 3;</code>
     */
    public Builder setUserUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userUuid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.appdirect.event.GDPRRequest)
  }

  // @@protoc_insertion_point(class_scope:com.appdirect.event.GDPRRequest)
  private static final com.appdirect.event.GDPRRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.appdirect.event.GDPRRequest();
  }

  public static com.appdirect.event.GDPRRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GDPRRequest>
      PARSER = new com.google.protobuf.AbstractParser<GDPRRequest>() {
    public GDPRRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GDPRRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GDPRRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GDPRRequest> getParserForType() {
    return PARSER;
  }

  public com.appdirect.event.GDPRRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

