// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: importableApplication.proto

package com.appdirect.event;

public interface ImportableApplicationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.ImportableApplication)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.Application application = 1;</code>
   */
  boolean hasApplication();
  /**
   * <code>optional .com.appdirect.event.Application application = 1;</code>
   */
  com.appdirect.event.Application getApplication();
  /**
   * <code>optional .com.appdirect.event.Application application = 1;</code>
   */
  com.appdirect.event.ApplicationOrBuilder getApplicationOrBuilder();

  /**
   * <code>optional string globalIdentifier = 2;</code>
   */
  java.lang.String getGlobalIdentifier();
  /**
   * <code>optional string globalIdentifier = 2;</code>
   */
  com.google.protobuf.ByteString
      getGlobalIdentifierBytes();
}
