// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invoice.event.proto

package com.appdirect.event;

public interface InvoiceCreatedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.InvoiceCreated)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.Invoice invoice = 1;</code>
   */
  boolean hasInvoice();
  /**
   * <code>optional .com.appdirect.event.Invoice invoice = 1;</code>
   */
  com.appdirect.event.Invoice getInvoice();
  /**
   * <code>optional .com.appdirect.event.Invoice invoice = 1;</code>
   */
  com.appdirect.event.InvoiceOrBuilder getInvoiceOrBuilder();

  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 2;</code>
   */
  boolean hasMetadata();
  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 2;</code>
   */
  com.appdirect.event.Metadata getMetadata();
  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 2;</code>
   */
  com.appdirect.event.MetadataOrBuilder getMetadataOrBuilder();
}
