// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invoice.proto

package com.appdirect.event;

/**
 * Protobuf type {@code com.appdirect.event.Invoice}
 */
public  final class Invoice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.appdirect.event.Invoice)
    InvoiceOrBuilder {
  // Use Invoice.newBuilder() to construct.
  private Invoice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Invoice() {
    creationDate_ = 0L;
    dueDate_ = 0L;
    status_ = "";
    total_ = 0D;
    currency_ = "";
    companyUuid_ = "";
    userUuid_ = "";
    invoiceline_ = java.util.Collections.emptyList();
    isRefund_ = false;
    isCreditNote_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Invoice(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.appdirect.event.Resource.Builder subBuilder = null;
            if (resource_ != null) {
              subBuilder = resource_.toBuilder();
            }
            resource_ = input.readMessage(com.appdirect.event.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resource_);
              resource_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            creationDate_ = input.readInt64();
            break;
          }
          case 24: {

            dueDate_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 41: {

            total_ = input.readDouble();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            currency_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            companyUuid_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            userUuid_ = s;
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              invoiceline_ = new java.util.ArrayList<com.appdirect.event.InvoiceLine>();
              mutable_bitField0_ |= 0x00000100;
            }
            invoiceline_.add(
                input.readMessage(com.appdirect.event.InvoiceLine.parser(), extensionRegistry));
            break;
          }
          case 80: {

            isRefund_ = input.readBool();
            break;
          }
          case 88: {

            isCreditNote_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        invoiceline_ = java.util.Collections.unmodifiableList(invoiceline_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.appdirect.event.InvoiceOuterClass.internal_static_com_appdirect_event_Invoice_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.appdirect.event.InvoiceOuterClass.internal_static_com_appdirect_event_Invoice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.appdirect.event.Invoice.class, com.appdirect.event.Invoice.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_FIELD_NUMBER = 1;
  private com.appdirect.event.Resource resource_;
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  public boolean hasResource() {
    return resource_ != null;
  }
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  public com.appdirect.event.Resource getResource() {
    return resource_ == null ? com.appdirect.event.Resource.getDefaultInstance() : resource_;
  }
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  public com.appdirect.event.ResourceOrBuilder getResourceOrBuilder() {
    return getResource();
  }

  public static final int CREATIONDATE_FIELD_NUMBER = 2;
  private long creationDate_;
  /**
   * <code>optional int64 creationDate = 2;</code>
   */
  public long getCreationDate() {
    return creationDate_;
  }

  public static final int DUEDATE_FIELD_NUMBER = 3;
  private long dueDate_;
  /**
   * <code>optional int64 dueDate = 3;</code>
   */
  public long getDueDate() {
    return dueDate_;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private volatile java.lang.Object status_;
  /**
   * <code>optional string status = 4;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>optional string status = 4;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_FIELD_NUMBER = 5;
  private double total_;
  /**
   * <code>optional double total = 5;</code>
   */
  public double getTotal() {
    return total_;
  }

  public static final int CURRENCY_FIELD_NUMBER = 6;
  private volatile java.lang.Object currency_;
  /**
   * <code>optional string currency = 6;</code>
   */
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <code>optional string currency = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANYUUID_FIELD_NUMBER = 7;
  private volatile java.lang.Object companyUuid_;
  /**
   * <code>optional string companyUuid = 7;</code>
   */
  public java.lang.String getCompanyUuid() {
    java.lang.Object ref = companyUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyUuid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string companyUuid = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCompanyUuidBytes() {
    java.lang.Object ref = companyUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERUUID_FIELD_NUMBER = 8;
  private volatile java.lang.Object userUuid_;
  /**
   * <code>optional string userUuid = 8;</code>
   */
  public java.lang.String getUserUuid() {
    java.lang.Object ref = userUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userUuid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string userUuid = 8;</code>
   */
  public com.google.protobuf.ByteString
      getUserUuidBytes() {
    java.lang.Object ref = userUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVOICELINE_FIELD_NUMBER = 9;
  private java.util.List<com.appdirect.event.InvoiceLine> invoiceline_;
  /**
   * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
   */
  public java.util.List<com.appdirect.event.InvoiceLine> getInvoicelineList() {
    return invoiceline_;
  }
  /**
   * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
   */
  public java.util.List<? extends com.appdirect.event.InvoiceLineOrBuilder> 
      getInvoicelineOrBuilderList() {
    return invoiceline_;
  }
  /**
   * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
   */
  public int getInvoicelineCount() {
    return invoiceline_.size();
  }
  /**
   * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
   */
  public com.appdirect.event.InvoiceLine getInvoiceline(int index) {
    return invoiceline_.get(index);
  }
  /**
   * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
   */
  public com.appdirect.event.InvoiceLineOrBuilder getInvoicelineOrBuilder(
      int index) {
    return invoiceline_.get(index);
  }

  public static final int ISREFUND_FIELD_NUMBER = 10;
  private boolean isRefund_;
  /**
   * <code>optional bool isRefund = 10;</code>
   */
  public boolean getIsRefund() {
    return isRefund_;
  }

  public static final int ISCREDITNOTE_FIELD_NUMBER = 11;
  private boolean isCreditNote_;
  /**
   * <code>optional bool isCreditNote = 11;</code>
   */
  public boolean getIsCreditNote() {
    return isCreditNote_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resource_ != null) {
      output.writeMessage(1, getResource());
    }
    if (creationDate_ != 0L) {
      output.writeInt64(2, creationDate_);
    }
    if (dueDate_ != 0L) {
      output.writeInt64(3, dueDate_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
    }
    if (total_ != 0D) {
      output.writeDouble(5, total_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, currency_);
    }
    if (!getCompanyUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, companyUuid_);
    }
    if (!getUserUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userUuid_);
    }
    for (int i = 0; i < invoiceline_.size(); i++) {
      output.writeMessage(9, invoiceline_.get(i));
    }
    if (isRefund_ != false) {
      output.writeBool(10, isRefund_);
    }
    if (isCreditNote_ != false) {
      output.writeBool(11, isCreditNote_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    if (creationDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, creationDate_);
    }
    if (dueDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, dueDate_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
    }
    if (total_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, total_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, currency_);
    }
    if (!getCompanyUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, companyUuid_);
    }
    if (!getUserUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, userUuid_);
    }
    for (int i = 0; i < invoiceline_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, invoiceline_.get(i));
    }
    if (isRefund_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isRefund_);
    }
    if (isCreditNote_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, isCreditNote_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.appdirect.event.Invoice)) {
      return super.equals(obj);
    }
    com.appdirect.event.Invoice other = (com.appdirect.event.Invoice) obj;

    boolean result = true;
    result = result && (hasResource() == other.hasResource());
    if (hasResource()) {
      result = result && getResource()
          .equals(other.getResource());
    }
    result = result && (getCreationDate()
        == other.getCreationDate());
    result = result && (getDueDate()
        == other.getDueDate());
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && (
        java.lang.Double.doubleToLongBits(getTotal())
        == java.lang.Double.doubleToLongBits(
            other.getTotal()));
    result = result && getCurrency()
        .equals(other.getCurrency());
    result = result && getCompanyUuid()
        .equals(other.getCompanyUuid());
    result = result && getUserUuid()
        .equals(other.getUserUuid());
    result = result && getInvoicelineList()
        .equals(other.getInvoicelineList());
    result = result && (getIsRefund()
        == other.getIsRefund());
    result = result && (getIsCreditNote()
        == other.getIsCreditNote());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    hash = (37 * hash) + CREATIONDATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreationDate());
    hash = (37 * hash) + DUEDATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDueDate());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTotal()));
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrency().hashCode();
    hash = (37 * hash) + COMPANYUUID_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyUuid().hashCode();
    hash = (37 * hash) + USERUUID_FIELD_NUMBER;
    hash = (53 * hash) + getUserUuid().hashCode();
    if (getInvoicelineCount() > 0) {
      hash = (37 * hash) + INVOICELINE_FIELD_NUMBER;
      hash = (53 * hash) + getInvoicelineList().hashCode();
    }
    hash = (37 * hash) + ISREFUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsRefund());
    hash = (37 * hash) + ISCREDITNOTE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCreditNote());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.appdirect.event.Invoice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appdirect.event.Invoice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appdirect.event.Invoice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appdirect.event.Invoice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appdirect.event.Invoice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appdirect.event.Invoice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appdirect.event.Invoice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.appdirect.event.Invoice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appdirect.event.Invoice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appdirect.event.Invoice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.appdirect.event.Invoice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.appdirect.event.Invoice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.appdirect.event.Invoice)
      com.appdirect.event.InvoiceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appdirect.event.InvoiceOuterClass.internal_static_com_appdirect_event_Invoice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appdirect.event.InvoiceOuterClass.internal_static_com_appdirect_event_Invoice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.appdirect.event.Invoice.class, com.appdirect.event.Invoice.Builder.class);
    }

    // Construct using com.appdirect.event.Invoice.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInvoicelineFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (resourceBuilder_ == null) {
        resource_ = null;
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }
      creationDate_ = 0L;

      dueDate_ = 0L;

      status_ = "";

      total_ = 0D;

      currency_ = "";

      companyUuid_ = "";

      userUuid_ = "";

      if (invoicelineBuilder_ == null) {
        invoiceline_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
      } else {
        invoicelineBuilder_.clear();
      }
      isRefund_ = false;

      isCreditNote_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.appdirect.event.InvoiceOuterClass.internal_static_com_appdirect_event_Invoice_descriptor;
    }

    public com.appdirect.event.Invoice getDefaultInstanceForType() {
      return com.appdirect.event.Invoice.getDefaultInstance();
    }

    public com.appdirect.event.Invoice build() {
      com.appdirect.event.Invoice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.appdirect.event.Invoice buildPartial() {
      com.appdirect.event.Invoice result = new com.appdirect.event.Invoice(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (resourceBuilder_ == null) {
        result.resource_ = resource_;
      } else {
        result.resource_ = resourceBuilder_.build();
      }
      result.creationDate_ = creationDate_;
      result.dueDate_ = dueDate_;
      result.status_ = status_;
      result.total_ = total_;
      result.currency_ = currency_;
      result.companyUuid_ = companyUuid_;
      result.userUuid_ = userUuid_;
      if (invoicelineBuilder_ == null) {
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          invoiceline_ = java.util.Collections.unmodifiableList(invoiceline_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.invoiceline_ = invoiceline_;
      } else {
        result.invoiceline_ = invoicelineBuilder_.build();
      }
      result.isRefund_ = isRefund_;
      result.isCreditNote_ = isCreditNote_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.appdirect.event.Invoice) {
        return mergeFrom((com.appdirect.event.Invoice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.appdirect.event.Invoice other) {
      if (other == com.appdirect.event.Invoice.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (other.getCreationDate() != 0L) {
        setCreationDate(other.getCreationDate());
      }
      if (other.getDueDate() != 0L) {
        setDueDate(other.getDueDate());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (other.getTotal() != 0D) {
        setTotal(other.getTotal());
      }
      if (!other.getCurrency().isEmpty()) {
        currency_ = other.currency_;
        onChanged();
      }
      if (!other.getCompanyUuid().isEmpty()) {
        companyUuid_ = other.companyUuid_;
        onChanged();
      }
      if (!other.getUserUuid().isEmpty()) {
        userUuid_ = other.userUuid_;
        onChanged();
      }
      if (invoicelineBuilder_ == null) {
        if (!other.invoiceline_.isEmpty()) {
          if (invoiceline_.isEmpty()) {
            invoiceline_ = other.invoiceline_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureInvoicelineIsMutable();
            invoiceline_.addAll(other.invoiceline_);
          }
          onChanged();
        }
      } else {
        if (!other.invoiceline_.isEmpty()) {
          if (invoicelineBuilder_.isEmpty()) {
            invoicelineBuilder_.dispose();
            invoicelineBuilder_ = null;
            invoiceline_ = other.invoiceline_;
            bitField0_ = (bitField0_ & ~0x00000100);
            invoicelineBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInvoicelineFieldBuilder() : null;
          } else {
            invoicelineBuilder_.addAllMessages(other.invoiceline_);
          }
        }
      }
      if (other.getIsRefund() != false) {
        setIsRefund(other.getIsRefund());
      }
      if (other.getIsCreditNote() != false) {
        setIsCreditNote(other.getIsCreditNote());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.appdirect.event.Invoice parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.appdirect.event.Invoice) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.appdirect.event.Resource resource_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.appdirect.event.Resource, com.appdirect.event.Resource.Builder, com.appdirect.event.ResourceOrBuilder> resourceBuilder_;
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public boolean hasResource() {
      return resourceBuilder_ != null || resource_ != null;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public com.appdirect.event.Resource getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? com.appdirect.event.Resource.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder setResource(com.appdirect.event.Resource value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        resourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder setResource(
        com.appdirect.event.Resource.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder mergeResource(com.appdirect.event.Resource value) {
      if (resourceBuilder_ == null) {
        if (resource_ != null) {
          resource_ =
            com.appdirect.event.Resource.newBuilder(resource_).mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        resourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder clearResource() {
      if (resourceBuilder_ == null) {
        resource_ = null;
        onChanged();
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public com.appdirect.event.Resource.Builder getResourceBuilder() {
      
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public com.appdirect.event.ResourceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            com.appdirect.event.Resource.getDefaultInstance() : resource_;
      }
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.appdirect.event.Resource, com.appdirect.event.Resource.Builder, com.appdirect.event.ResourceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.appdirect.event.Resource, com.appdirect.event.Resource.Builder, com.appdirect.event.ResourceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private long creationDate_ ;
    /**
     * <code>optional int64 creationDate = 2;</code>
     */
    public long getCreationDate() {
      return creationDate_;
    }
    /**
     * <code>optional int64 creationDate = 2;</code>
     */
    public Builder setCreationDate(long value) {
      
      creationDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 creationDate = 2;</code>
     */
    public Builder clearCreationDate() {
      
      creationDate_ = 0L;
      onChanged();
      return this;
    }

    private long dueDate_ ;
    /**
     * <code>optional int64 dueDate = 3;</code>
     */
    public long getDueDate() {
      return dueDate_;
    }
    /**
     * <code>optional int64 dueDate = 3;</code>
     */
    public Builder setDueDate(long value) {
      
      dueDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 dueDate = 3;</code>
     */
    public Builder clearDueDate() {
      
      dueDate_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>optional string status = 4;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string status = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string status = 4;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 4;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>optional string status = 4;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private double total_ ;
    /**
     * <code>optional double total = 5;</code>
     */
    public double getTotal() {
      return total_;
    }
    /**
     * <code>optional double total = 5;</code>
     */
    public Builder setTotal(double value) {
      
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double total = 5;</code>
     */
    public Builder clearTotal() {
      
      total_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <code>optional string currency = 6;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string currency = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string currency = 6;</code>
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currency_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string currency = 6;</code>
     */
    public Builder clearCurrency() {
      
      currency_ = getDefaultInstance().getCurrency();
      onChanged();
      return this;
    }
    /**
     * <code>optional string currency = 6;</code>
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currency_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyUuid_ = "";
    /**
     * <code>optional string companyUuid = 7;</code>
     */
    public java.lang.String getCompanyUuid() {
      java.lang.Object ref = companyUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string companyUuid = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyUuidBytes() {
      java.lang.Object ref = companyUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string companyUuid = 7;</code>
     */
    public Builder setCompanyUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string companyUuid = 7;</code>
     */
    public Builder clearCompanyUuid() {
      
      companyUuid_ = getDefaultInstance().getCompanyUuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string companyUuid = 7;</code>
     */
    public Builder setCompanyUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userUuid_ = "";
    /**
     * <code>optional string userUuid = 8;</code>
     */
    public java.lang.String getUserUuid() {
      java.lang.Object ref = userUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string userUuid = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUserUuidBytes() {
      java.lang.Object ref = userUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string userUuid = 8;</code>
     */
    public Builder setUserUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string userUuid = 8;</code>
     */
    public Builder clearUserUuid() {
      
      userUuid_ = getDefaultInstance().getUserUuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string userUuid = 8;</code>
     */
    public Builder setUserUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userUuid_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.appdirect.event.InvoiceLine> invoiceline_ =
      java.util.Collections.emptyList();
    private void ensureInvoicelineIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        invoiceline_ = new java.util.ArrayList<com.appdirect.event.InvoiceLine>(invoiceline_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.appdirect.event.InvoiceLine, com.appdirect.event.InvoiceLine.Builder, com.appdirect.event.InvoiceLineOrBuilder> invoicelineBuilder_;

    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public java.util.List<com.appdirect.event.InvoiceLine> getInvoicelineList() {
      if (invoicelineBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invoiceline_);
      } else {
        return invoicelineBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public int getInvoicelineCount() {
      if (invoicelineBuilder_ == null) {
        return invoiceline_.size();
      } else {
        return invoicelineBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public com.appdirect.event.InvoiceLine getInvoiceline(int index) {
      if (invoicelineBuilder_ == null) {
        return invoiceline_.get(index);
      } else {
        return invoicelineBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public Builder setInvoiceline(
        int index, com.appdirect.event.InvoiceLine value) {
      if (invoicelineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicelineIsMutable();
        invoiceline_.set(index, value);
        onChanged();
      } else {
        invoicelineBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public Builder setInvoiceline(
        int index, com.appdirect.event.InvoiceLine.Builder builderForValue) {
      if (invoicelineBuilder_ == null) {
        ensureInvoicelineIsMutable();
        invoiceline_.set(index, builderForValue.build());
        onChanged();
      } else {
        invoicelineBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public Builder addInvoiceline(com.appdirect.event.InvoiceLine value) {
      if (invoicelineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicelineIsMutable();
        invoiceline_.add(value);
        onChanged();
      } else {
        invoicelineBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public Builder addInvoiceline(
        int index, com.appdirect.event.InvoiceLine value) {
      if (invoicelineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicelineIsMutable();
        invoiceline_.add(index, value);
        onChanged();
      } else {
        invoicelineBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public Builder addInvoiceline(
        com.appdirect.event.InvoiceLine.Builder builderForValue) {
      if (invoicelineBuilder_ == null) {
        ensureInvoicelineIsMutable();
        invoiceline_.add(builderForValue.build());
        onChanged();
      } else {
        invoicelineBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public Builder addInvoiceline(
        int index, com.appdirect.event.InvoiceLine.Builder builderForValue) {
      if (invoicelineBuilder_ == null) {
        ensureInvoicelineIsMutable();
        invoiceline_.add(index, builderForValue.build());
        onChanged();
      } else {
        invoicelineBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public Builder addAllInvoiceline(
        java.lang.Iterable<? extends com.appdirect.event.InvoiceLine> values) {
      if (invoicelineBuilder_ == null) {
        ensureInvoicelineIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invoiceline_);
        onChanged();
      } else {
        invoicelineBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public Builder clearInvoiceline() {
      if (invoicelineBuilder_ == null) {
        invoiceline_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        invoicelineBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public Builder removeInvoiceline(int index) {
      if (invoicelineBuilder_ == null) {
        ensureInvoicelineIsMutable();
        invoiceline_.remove(index);
        onChanged();
      } else {
        invoicelineBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public com.appdirect.event.InvoiceLine.Builder getInvoicelineBuilder(
        int index) {
      return getInvoicelineFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public com.appdirect.event.InvoiceLineOrBuilder getInvoicelineOrBuilder(
        int index) {
      if (invoicelineBuilder_ == null) {
        return invoiceline_.get(index);  } else {
        return invoicelineBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public java.util.List<? extends com.appdirect.event.InvoiceLineOrBuilder> 
         getInvoicelineOrBuilderList() {
      if (invoicelineBuilder_ != null) {
        return invoicelineBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invoiceline_);
      }
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public com.appdirect.event.InvoiceLine.Builder addInvoicelineBuilder() {
      return getInvoicelineFieldBuilder().addBuilder(
          com.appdirect.event.InvoiceLine.getDefaultInstance());
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public com.appdirect.event.InvoiceLine.Builder addInvoicelineBuilder(
        int index) {
      return getInvoicelineFieldBuilder().addBuilder(
          index, com.appdirect.event.InvoiceLine.getDefaultInstance());
    }
    /**
     * <code>repeated .com.appdirect.event.InvoiceLine invoiceline = 9;</code>
     */
    public java.util.List<com.appdirect.event.InvoiceLine.Builder> 
         getInvoicelineBuilderList() {
      return getInvoicelineFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.appdirect.event.InvoiceLine, com.appdirect.event.InvoiceLine.Builder, com.appdirect.event.InvoiceLineOrBuilder> 
        getInvoicelineFieldBuilder() {
      if (invoicelineBuilder_ == null) {
        invoicelineBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.appdirect.event.InvoiceLine, com.appdirect.event.InvoiceLine.Builder, com.appdirect.event.InvoiceLineOrBuilder>(
                invoiceline_,
                ((bitField0_ & 0x00000100) == 0x00000100),
                getParentForChildren(),
                isClean());
        invoiceline_ = null;
      }
      return invoicelineBuilder_;
    }

    private boolean isRefund_ ;
    /**
     * <code>optional bool isRefund = 10;</code>
     */
    public boolean getIsRefund() {
      return isRefund_;
    }
    /**
     * <code>optional bool isRefund = 10;</code>
     */
    public Builder setIsRefund(boolean value) {
      
      isRefund_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isRefund = 10;</code>
     */
    public Builder clearIsRefund() {
      
      isRefund_ = false;
      onChanged();
      return this;
    }

    private boolean isCreditNote_ ;
    /**
     * <code>optional bool isCreditNote = 11;</code>
     */
    public boolean getIsCreditNote() {
      return isCreditNote_;
    }
    /**
     * <code>optional bool isCreditNote = 11;</code>
     */
    public Builder setIsCreditNote(boolean value) {
      
      isCreditNote_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isCreditNote = 11;</code>
     */
    public Builder clearIsCreditNote() {
      
      isCreditNote_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.appdirect.event.Invoice)
  }

  // @@protoc_insertion_point(class_scope:com.appdirect.event.Invoice)
  private static final com.appdirect.event.Invoice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.appdirect.event.Invoice();
  }

  public static com.appdirect.event.Invoice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Invoice>
      PARSER = new com.google.protobuf.AbstractParser<Invoice>() {
    public Invoice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Invoice(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Invoice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Invoice> getParserForType() {
    return PARSER;
  }

  public com.appdirect.event.Invoice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

