// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: membership.proto

package com.appdirect.event;

public interface MembershipRoleChangedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.MembershipRoleChanged)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.Membership membership = 1;</code>
   */
  boolean hasMembership();
  /**
   * <code>optional .com.appdirect.event.Membership membership = 1;</code>
   */
  com.appdirect.event.Membership getMembership();
  /**
   * <code>optional .com.appdirect.event.Membership membership = 1;</code>
   */
  com.appdirect.event.MembershipOrBuilder getMembershipOrBuilder();

  /**
   * <code>repeated string roles = 2;</code>
   */
  java.util.List<java.lang.String>
      getRolesList();
  /**
   * <code>repeated string roles = 2;</code>
   */
  int getRolesCount();
  /**
   * <code>repeated string roles = 2;</code>
   */
  java.lang.String getRoles(int index);
  /**
   * <code>repeated string roles = 2;</code>
   */
  com.google.protobuf.ByteString
      getRolesBytes(int index);

  /**
   * <code>repeated string gainedRoles = 3;</code>
   */
  java.util.List<java.lang.String>
      getGainedRolesList();
  /**
   * <code>repeated string gainedRoles = 3;</code>
   */
  int getGainedRolesCount();
  /**
   * <code>repeated string gainedRoles = 3;</code>
   */
  java.lang.String getGainedRoles(int index);
  /**
   * <code>repeated string gainedRoles = 3;</code>
   */
  com.google.protobuf.ByteString
      getGainedRolesBytes(int index);

  /**
   * <code>repeated string lostRoles = 4;</code>
   */
  java.util.List<java.lang.String>
      getLostRolesList();
  /**
   * <code>repeated string lostRoles = 4;</code>
   */
  int getLostRolesCount();
  /**
   * <code>repeated string lostRoles = 4;</code>
   */
  java.lang.String getLostRoles(int index);
  /**
   * <code>repeated string lostRoles = 4;</code>
   */
  com.google.protobuf.ByteString
      getLostRolesBytes(int index);

  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 5;</code>
   */
  boolean hasMetadata();
  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 5;</code>
   */
  com.appdirect.event.Metadata getMetadata();
  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 5;</code>
   */
  com.appdirect.event.MetadataOrBuilder getMetadataOrBuilder();
}
