// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: membership.proto

package com.appdirect.event;

public final class MembershipOuterClass {
  private MembershipOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_Membership_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_Membership_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_MembershipCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_MembershipCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_MembershipUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_MembershipUpdated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_MembershipDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_MembershipDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_MembershipRoleChanged_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_MembershipRoleChanged_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020membership.proto\022\023com.appdirect.event\032" +
      "\016resource.proto\032\016metadata.proto\"\246\001\n\nMemb" +
      "ership\022/\n\010resource\030\001 \001(\0132\035.com.appdirect" +
      ".event.Resource\022\020\n\010userUuid\030\002 \001(\t\022\025\n\ruse" +
      "rFirstName\030\003 \001(\t\022\024\n\014userLastName\030\004 \001(\t\022\023" +
      "\n\013companyUuid\030\005 \001(\t\022\023\n\013companyName\030\006 \001(\t" +
      "\"y\n\021MembershipCreated\0223\n\nmembership\030\001 \001(" +
      "\0132\037.com.appdirect.event.Membership\022/\n\010me" +
      "tadata\030\002 \001(\0132\035.com.appdirect.event.Metad" +
      "ata\"y\n\021MembershipUpdated\0223\n\nmembership\030\001",
      " \001(\0132\037.com.appdirect.event.Membership\022/\n" +
      "\010metadata\030\002 \001(\0132\035.com.appdirect.event.Me" +
      "tadata\"y\n\021MembershipDeleted\0223\n\nmembershi" +
      "p\030\001 \001(\0132\037.com.appdirect.event.Membership" +
      "\022/\n\010metadata\030\002 \001(\0132\035.com.appdirect.event" +
      ".Metadata\"\264\001\n\025MembershipRoleChanged\0223\n\nm" +
      "embership\030\001 \001(\0132\037.com.appdirect.event.Me" +
      "mbership\022\r\n\005roles\030\002 \003(\t\022\023\n\013gainedRoles\030\003" +
      " \003(\t\022\021\n\tlostRoles\030\004 \003(\t\022/\n\010metadata\030\005 \001(" +
      "\0132\035.com.appdirect.event.MetadataB\002P\001b\006pr",
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.appdirect.event.ResourceOuterClass.getDescriptor(),
          com.appdirect.event.MetadataOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_appdirect_event_Membership_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appdirect_event_Membership_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_Membership_descriptor,
        new java.lang.String[] { "Resource", "UserUuid", "UserFirstName", "UserLastName", "CompanyUuid", "CompanyName", });
    internal_static_com_appdirect_event_MembershipCreated_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_appdirect_event_MembershipCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_MembershipCreated_descriptor,
        new java.lang.String[] { "Membership", "Metadata", });
    internal_static_com_appdirect_event_MembershipUpdated_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_appdirect_event_MembershipUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_MembershipUpdated_descriptor,
        new java.lang.String[] { "Membership", "Metadata", });
    internal_static_com_appdirect_event_MembershipDeleted_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_appdirect_event_MembershipDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_MembershipDeleted_descriptor,
        new java.lang.String[] { "Membership", "Metadata", });
    internal_static_com_appdirect_event_MembershipRoleChanged_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_appdirect_event_MembershipRoleChanged_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_MembershipRoleChanged_descriptor,
        new java.lang.String[] { "Membership", "Roles", "GainedRoles", "LostRoles", "Metadata", });
    com.appdirect.event.ResourceOuterClass.getDescriptor();
    com.appdirect.event.MetadataOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
