// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MFAMigrationAcknowledgement.proto

package com.appdirect.event;

public final class MFAMigrationAcknowledgementOuterClass {
  private MFAMigrationAcknowledgementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_MFAMigrationAcknowledgement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_MFAMigrationAcknowledgement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!MFAMigrationAcknowledgement.proto\022\023com" +
      ".appdirect.event\"\263\001\n\033MFAMigrationAcknowl" +
      "edgement\022\025\n\rmigrationDate\030\001 \001(\003\0220\n\004type\030" +
      "\002 \001(\0162\".com.appdirect.event.MigrationTyp" +
      "e\022\016\n\006tenant\030\003 \001(\t\022\023\n\013companyUuid\030\004 \001(\t\022\020" +
      "\n\010userUuid\030\005 \001(\t\022\024\n\014phone_number\030\006 \001(\t*\211" +
      "\001\n\rMigrationType\022\026\n\022MFA_GLOBAL_SETTING\020\000" +
      "\022\026\n\022MFA_TENANT_SETTING\020\001\022\027\n\023MFA_COMPANY_" +
      "SETTING\020\002\022\024\n\020MFA_USER_SETTING\020\003\022\031\n\025MFA_U" +
      "SER_PHONE_NUMBER\020\004B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_appdirect_event_MFAMigrationAcknowledgement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appdirect_event_MFAMigrationAcknowledgement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_MFAMigrationAcknowledgement_descriptor,
        new java.lang.String[] { "MigrationDate", "Type", "Tenant", "CompanyUuid", "UserUuid", "PhoneNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
