// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MFASettings.proto

package com.appdirect.event;

public interface MFASettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.MFASettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  boolean hasResource();
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  com.appdirect.event.Resource getResource();
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  com.appdirect.event.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <code>optional bool enabled = 2;</code>
   */
  boolean getEnabled();

  /**
   * <code>repeated string requiredRoles = 3;</code>
   */
  java.util.List<java.lang.String>
      getRequiredRolesList();
  /**
   * <code>repeated string requiredRoles = 3;</code>
   */
  int getRequiredRolesCount();
  /**
   * <code>repeated string requiredRoles = 3;</code>
   */
  java.lang.String getRequiredRoles(int index);
  /**
   * <code>repeated string requiredRoles = 3;</code>
   */
  com.google.protobuf.ByteString
      getRequiredRolesBytes(int index);

  /**
   * <code>optional int64 tokenTolerance = 4;</code>
   */
  long getTokenTolerance();

  /**
   * <code>optional bool trustedDeviceEnabled = 5;</code>
   */
  boolean getTrustedDeviceEnabled();

  /**
   * <code>optional int32 trustedDays = 6;</code>
   */
  int getTrustedDays();

  /**
   * <code>optional string type = 7;</code>
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 7;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional string entityId = 8;</code>
   */
  java.lang.String getEntityId();
  /**
   * <code>optional string entityId = 8;</code>
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>optional string securityKeyEnabled = 9;</code>
   */
  java.lang.String getSecurityKeyEnabled();
  /**
   * <code>optional string securityKeyEnabled = 9;</code>
   */
  com.google.protobuf.ByteString
      getSecurityKeyEnabledBytes();

  /**
   * <code>optional bool superuserExcluded = 10;</code>
   */
  boolean getSuperuserExcluded();

  /**
   * <code>optional bool authenticationViaSms = 11;</code>
   */
  boolean getAuthenticationViaSms();
}
