// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

package com.appdirect.event;

public final class PaymentOuterClass {
  private PaymentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_PaymentResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_PaymentResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_Payment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_Payment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayment.proto\022\023com.appdirect.event\032\016re" +
      "source.proto\"C\n\rPaymentResult\022\014\n\004code\030\001 " +
      "\001(\t\022\017\n\007meaning\030\002 \001(\t\022\023\n\013billingCode\030\003 \001(" +
      "\003\"\220\002\n\007Payment\022/\n\010resource\030\001 \001(\0132\035.com.ap" +
      "pdirect.event.Resource\022\023\n\013paymentDate\030\002 " +
      "\001(\003\022\016\n\006amount\030\003 \001(\001\022\020\n\010currency\030\004 \001(\t\0222\n" +
      "\006result\030\005 \001(\0132\".com.appdirect.event.Paym" +
      "entResult\022\016\n\006method\030\006 \001(\t\022\025\n\rtransaction" +
      "Id\030\007 \001(\t\022\020\n\010userUuid\030\010 \001(\t\022\023\n\013companyUui" +
      "d\030\t \001(\t\022\033\n\023processedByUserUuid\030\n \001(\tB\002P\001",
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.appdirect.event.ResourceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_appdirect_event_PaymentResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appdirect_event_PaymentResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_PaymentResult_descriptor,
        new java.lang.String[] { "Code", "Meaning", "BillingCode", });
    internal_static_com_appdirect_event_Payment_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_appdirect_event_Payment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_Payment_descriptor,
        new java.lang.String[] { "Resource", "PaymentDate", "Amount", "Currency", "Result", "Method", "TransactionId", "UserUuid", "CompanyUuid", "ProcessedByUserUuid", });
    com.appdirect.event.ResourceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
