// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rolePermissions.proto

package com.appdirect.event;

public interface PermissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.Permission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string authority = 1;</code>
   */
  java.lang.String getAuthority();
  /**
   * <code>optional string authority = 1;</code>
   */
  com.google.protobuf.ByteString
      getAuthorityBytes();

  /**
   * <code>optional string capability = 2;</code>
   */
  java.lang.String getCapability();
  /**
   * <code>optional string capability = 2;</code>
   */
  com.google.protobuf.ByteString
      getCapabilityBytes();

  /**
   * <code>optional string permissionCategory = 3;</code>
   */
  java.lang.String getPermissionCategory();
  /**
   * <code>optional string permissionCategory = 3;</code>
   */
  com.google.protobuf.ByteString
      getPermissionCategoryBytes();

  /**
   * <code>optional .com.appdirect.event.Permission dependsOn = 4;</code>
   */
  boolean hasDependsOn();
  /**
   * <code>optional .com.appdirect.event.Permission dependsOn = 4;</code>
   */
  com.appdirect.event.Permission getDependsOn();
  /**
   * <code>optional .com.appdirect.event.Permission dependsOn = 4;</code>
   */
  com.appdirect.event.PermissionOrBuilder getDependsOnOrBuilder();
}
