// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource.proto

package com.appdirect.event;

public final class ResourceOuterClass {
  private ResourceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_Resource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_Resource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016resource.proto\022\023com.appdirect.event\032\016m" +
      "etadata.proto\"w\n\010Resource\022\n\n\002id\030\001 \001(\t\022\014\n" +
      "\004uuid\030\002 \001(\t\022\022\n\nexternalId\030\003 \001(\t\022\014\n\004type\030" +
      "\004 \001(\t\022/\n\010metadata\030\005 \001(\0132\035.com.appdirect." +
      "event.MetadataB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.appdirect.event.MetadataOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_appdirect_event_Resource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appdirect_event_Resource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_Resource_descriptor,
        new java.lang.String[] { "Id", "Uuid", "ExternalId", "Type", "Metadata", });
    com.appdirect.event.MetadataOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
