// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rolePermissions.proto

package com.appdirect.event;

public final class RolePermissionsOuterClass {
  private RolePermissionsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_Permission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_Permission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_RolePermissions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_RolePermissions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025rolePermissions.proto\022\023com.appdirect.e" +
      "vent\032\016resource.proto\"\203\001\n\nPermission\022\021\n\ta" +
      "uthority\030\001 \001(\t\022\022\n\ncapability\030\002 \001(\t\022\032\n\022pe" +
      "rmissionCategory\030\003 \001(\t\0222\n\tdependsOn\030\004 \001(" +
      "\0132\037.com.appdirect.event.Permission\"\210\001\n\017R" +
      "olePermissions\022/\n\010resource\030\001 \001(\0132\035.com.a" +
      "ppdirect.event.Resource\022\016\n\006roleId\030\002 \001(\t\022" +
      "4\n\013permissions\030\005 \003(\0132\037.com.appdirect.eve" +
      "nt.PermissionB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.appdirect.event.ResourceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_appdirect_event_Permission_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appdirect_event_Permission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_Permission_descriptor,
        new java.lang.String[] { "Authority", "Capability", "PermissionCategory", "DependsOn", });
    internal_static_com_appdirect_event_RolePermissions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_appdirect_event_RolePermissions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_RolePermissions_descriptor,
        new java.lang.String[] { "Resource", "RoleId", "Permissions", });
    com.appdirect.event.ResourceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
