// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscription.event.proto

package com.appdirect.event;

public final class SubscriptionEvent {
  private SubscriptionEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_SubscriptionCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_SubscriptionCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_SubscriptionUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_SubscriptionUpdated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appdirect_event_SubscriptionDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appdirect_event_SubscriptionDeleted_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030subscription.event.proto\022\023com.appdirec" +
      "t.event\032\022subscription.proto\032\016metadata.pr" +
      "oto\"\177\n\023SubscriptionCreated\0227\n\014subscripti" +
      "on\030\001 \001(\0132!.com.appdirect.event.Subscript" +
      "ion\022/\n\010metadata\030\002 \001(\0132\035.com.appdirect.ev" +
      "ent.Metadata\"\177\n\023SubscriptionUpdated\0227\n\014s" +
      "ubscription\030\001 \001(\0132!.com.appdirect.event." +
      "Subscription\022/\n\010metadata\030\002 \001(\0132\035.com.app" +
      "direct.event.Metadata\"\177\n\023SubscriptionDel" +
      "eted\0227\n\014subscription\030\001 \001(\0132!.com.appdire",
      "ct.event.Subscription\022/\n\010metadata\030\002 \001(\0132" +
      "\035.com.appdirect.event.MetadataB\002P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.appdirect.event.SubscriptionOuterClass.getDescriptor(),
          com.appdirect.event.MetadataOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_appdirect_event_SubscriptionCreated_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appdirect_event_SubscriptionCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_SubscriptionCreated_descriptor,
        new java.lang.String[] { "Subscription", "Metadata", });
    internal_static_com_appdirect_event_SubscriptionUpdated_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_appdirect_event_SubscriptionUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_SubscriptionUpdated_descriptor,
        new java.lang.String[] { "Subscription", "Metadata", });
    internal_static_com_appdirect_event_SubscriptionDeleted_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_appdirect_event_SubscriptionDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appdirect_event_SubscriptionDeleted_descriptor,
        new java.lang.String[] { "Subscription", "Metadata", });
    com.appdirect.event.SubscriptionOuterClass.getDescriptor();
    com.appdirect.event.MetadataOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
