// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.appdirect.event;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  boolean hasResource();
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  com.appdirect.event.Resource getResource();
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  com.appdirect.event.ResourceOrBuilder getResourceOrBuilder();

  /**
   * <code>optional string first_name = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>optional string first_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string last_name = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>optional string last_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>optional string username = 4;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 4;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string email = 5;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 5;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
