// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.event.proto

package com.appdirect.event;

public interface UserRoleChangedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.UserRoleChanged)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .com.appdirect.event.User user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>optional .com.appdirect.event.User user = 1;</code>
   */
  com.appdirect.event.User getUser();
  /**
   * <code>optional .com.appdirect.event.User user = 1;</code>
   */
  com.appdirect.event.UserOrBuilder getUserOrBuilder();

  /**
   * <code>repeated string roles = 2;</code>
   */
  java.util.List<java.lang.String>
      getRolesList();
  /**
   * <code>repeated string roles = 2;</code>
   */
  int getRolesCount();
  /**
   * <code>repeated string roles = 2;</code>
   */
  java.lang.String getRoles(int index);
  /**
   * <code>repeated string roles = 2;</code>
   */
  com.google.protobuf.ByteString
      getRolesBytes(int index);

  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 3;</code>
   */
  boolean hasMetadata();
  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 3;</code>
   */
  com.appdirect.event.Metadata getMetadata();
  /**
   * <code>optional .com.appdirect.event.Metadata metadata = 3;</code>
   */
  com.appdirect.event.MetadataOrBuilder getMetadataOrBuilder();
}
