// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userTokenGrant.proto

package com.appdirect.event;

public interface UserTokenGrantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.appdirect.event.UserTokenGrant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string clientId = 1;</code>
   */
  java.lang.String getClientId();
  /**
   * <code>optional string clientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <code>optional string companyId = 2;</code>
   */
  java.lang.String getCompanyId();
  /**
   * <code>optional string companyId = 2;</code>
   */
  com.google.protobuf.ByteString
      getCompanyIdBytes();

  /**
   * <code>optional string userId = 3;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>optional string userId = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>optional string grantId = 4;</code>
   */
  java.lang.String getGrantId();
  /**
   * <code>optional string grantId = 4;</code>
   */
  com.google.protobuf.ByteString
      getGrantIdBytes();

  /**
   * <code>optional string tenant = 5;</code>
   */
  java.lang.String getTenant();
  /**
   * <code>optional string tenant = 5;</code>
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <code>map&lt;string, string&gt; parameters = 6;</code>
   */
  int getParametersCount();
  /**
   * <code>map&lt;string, string&gt; parameters = 6;</code>
   */
  boolean containsParameters(
      java.lang.String key);
  /**
   * Use {@link #getParametersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getParameters();
  /**
   * <code>map&lt;string, string&gt; parameters = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getParametersMap();
  /**
   * <code>map&lt;string, string&gt; parameters = 6;</code>
   */

  java.lang.String getParametersOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; parameters = 6;</code>
   */

  java.lang.String getParametersOrThrow(
      java.lang.String key);
}
