// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userMFASettings.proto

package com.appdirect.event;

/**
 * Protobuf type {@code com.appdirect.event.UserMFASettings}
 */
public  final class UserMFASettings extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.appdirect.event.UserMFASettings)
    UserMFASettingsOrBuilder {
  // Use UserMFASettings.newBuilder() to construct.
  private UserMFASettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserMFASettings() {
    pendingTotpSecret_ = "";
    totpSecret_ = "";
    lastUsedTotpSecret_ = "";
    isTotpAppEnabled_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UserMFASettings(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.appdirect.event.Resource.Builder subBuilder = null;
            if (resource_ != null) {
              subBuilder = resource_.toBuilder();
            }
            resource_ = input.readMessage(com.appdirect.event.Resource.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resource_);
              resource_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            pendingTotpSecret_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            totpSecret_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            lastUsedTotpSecret_ = s;
            break;
          }
          case 40: {

            isTotpAppEnabled_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.appdirect.event.UserMFASettingsOuterClass.internal_static_com_appdirect_event_UserMFASettings_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.appdirect.event.UserMFASettingsOuterClass.internal_static_com_appdirect_event_UserMFASettings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.appdirect.event.UserMFASettings.class, com.appdirect.event.UserMFASettings.Builder.class);
  }

  public static final int RESOURCE_FIELD_NUMBER = 1;
  private com.appdirect.event.Resource resource_;
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  public boolean hasResource() {
    return resource_ != null;
  }
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  public com.appdirect.event.Resource getResource() {
    return resource_ == null ? com.appdirect.event.Resource.getDefaultInstance() : resource_;
  }
  /**
   * <code>optional .com.appdirect.event.Resource resource = 1;</code>
   */
  public com.appdirect.event.ResourceOrBuilder getResourceOrBuilder() {
    return getResource();
  }

  public static final int PENDINGTOTPSECRET_FIELD_NUMBER = 2;
  private volatile java.lang.Object pendingTotpSecret_;
  /**
   * <code>optional string pendingTotpSecret = 2;</code>
   */
  public java.lang.String getPendingTotpSecret() {
    java.lang.Object ref = pendingTotpSecret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pendingTotpSecret_ = s;
      return s;
    }
  }
  /**
   * <code>optional string pendingTotpSecret = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPendingTotpSecretBytes() {
    java.lang.Object ref = pendingTotpSecret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pendingTotpSecret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTPSECRET_FIELD_NUMBER = 3;
  private volatile java.lang.Object totpSecret_;
  /**
   * <code>optional string totpSecret = 3;</code>
   */
  public java.lang.String getTotpSecret() {
    java.lang.Object ref = totpSecret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      totpSecret_ = s;
      return s;
    }
  }
  /**
   * <code>optional string totpSecret = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTotpSecretBytes() {
    java.lang.Object ref = totpSecret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      totpSecret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTUSEDTOTPSECRET_FIELD_NUMBER = 4;
  private volatile java.lang.Object lastUsedTotpSecret_;
  /**
   * <code>optional string lastUsedTotpSecret = 4;</code>
   */
  public java.lang.String getLastUsedTotpSecret() {
    java.lang.Object ref = lastUsedTotpSecret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastUsedTotpSecret_ = s;
      return s;
    }
  }
  /**
   * <code>optional string lastUsedTotpSecret = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLastUsedTotpSecretBytes() {
    java.lang.Object ref = lastUsedTotpSecret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastUsedTotpSecret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISTOTPAPPENABLED_FIELD_NUMBER = 5;
  private boolean isTotpAppEnabled_;
  /**
   * <code>optional bool isTotpAppEnabled = 5;</code>
   */
  public boolean getIsTotpAppEnabled() {
    return isTotpAppEnabled_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resource_ != null) {
      output.writeMessage(1, getResource());
    }
    if (!getPendingTotpSecretBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pendingTotpSecret_);
    }
    if (!getTotpSecretBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, totpSecret_);
    }
    if (!getLastUsedTotpSecretBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastUsedTotpSecret_);
    }
    if (isTotpAppEnabled_ != false) {
      output.writeBool(5, isTotpAppEnabled_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resource_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    if (!getPendingTotpSecretBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pendingTotpSecret_);
    }
    if (!getTotpSecretBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, totpSecret_);
    }
    if (!getLastUsedTotpSecretBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastUsedTotpSecret_);
    }
    if (isTotpAppEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isTotpAppEnabled_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.appdirect.event.UserMFASettings)) {
      return super.equals(obj);
    }
    com.appdirect.event.UserMFASettings other = (com.appdirect.event.UserMFASettings) obj;

    boolean result = true;
    result = result && (hasResource() == other.hasResource());
    if (hasResource()) {
      result = result && getResource()
          .equals(other.getResource());
    }
    result = result && getPendingTotpSecret()
        .equals(other.getPendingTotpSecret());
    result = result && getTotpSecret()
        .equals(other.getTotpSecret());
    result = result && getLastUsedTotpSecret()
        .equals(other.getLastUsedTotpSecret());
    result = result && (getIsTotpAppEnabled()
        == other.getIsTotpAppEnabled());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    hash = (37 * hash) + PENDINGTOTPSECRET_FIELD_NUMBER;
    hash = (53 * hash) + getPendingTotpSecret().hashCode();
    hash = (37 * hash) + TOTPSECRET_FIELD_NUMBER;
    hash = (53 * hash) + getTotpSecret().hashCode();
    hash = (37 * hash) + LASTUSEDTOTPSECRET_FIELD_NUMBER;
    hash = (53 * hash) + getLastUsedTotpSecret().hashCode();
    hash = (37 * hash) + ISTOTPAPPENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsTotpAppEnabled());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.appdirect.event.UserMFASettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appdirect.event.UserMFASettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appdirect.event.UserMFASettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.appdirect.event.UserMFASettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.appdirect.event.UserMFASettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appdirect.event.UserMFASettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appdirect.event.UserMFASettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.appdirect.event.UserMFASettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.appdirect.event.UserMFASettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.appdirect.event.UserMFASettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.appdirect.event.UserMFASettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.appdirect.event.UserMFASettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.appdirect.event.UserMFASettings)
      com.appdirect.event.UserMFASettingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appdirect.event.UserMFASettingsOuterClass.internal_static_com_appdirect_event_UserMFASettings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appdirect.event.UserMFASettingsOuterClass.internal_static_com_appdirect_event_UserMFASettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.appdirect.event.UserMFASettings.class, com.appdirect.event.UserMFASettings.Builder.class);
    }

    // Construct using com.appdirect.event.UserMFASettings.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (resourceBuilder_ == null) {
        resource_ = null;
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }
      pendingTotpSecret_ = "";

      totpSecret_ = "";

      lastUsedTotpSecret_ = "";

      isTotpAppEnabled_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.appdirect.event.UserMFASettingsOuterClass.internal_static_com_appdirect_event_UserMFASettings_descriptor;
    }

    public com.appdirect.event.UserMFASettings getDefaultInstanceForType() {
      return com.appdirect.event.UserMFASettings.getDefaultInstance();
    }

    public com.appdirect.event.UserMFASettings build() {
      com.appdirect.event.UserMFASettings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.appdirect.event.UserMFASettings buildPartial() {
      com.appdirect.event.UserMFASettings result = new com.appdirect.event.UserMFASettings(this);
      if (resourceBuilder_ == null) {
        result.resource_ = resource_;
      } else {
        result.resource_ = resourceBuilder_.build();
      }
      result.pendingTotpSecret_ = pendingTotpSecret_;
      result.totpSecret_ = totpSecret_;
      result.lastUsedTotpSecret_ = lastUsedTotpSecret_;
      result.isTotpAppEnabled_ = isTotpAppEnabled_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.appdirect.event.UserMFASettings) {
        return mergeFrom((com.appdirect.event.UserMFASettings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.appdirect.event.UserMFASettings other) {
      if (other == com.appdirect.event.UserMFASettings.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (!other.getPendingTotpSecret().isEmpty()) {
        pendingTotpSecret_ = other.pendingTotpSecret_;
        onChanged();
      }
      if (!other.getTotpSecret().isEmpty()) {
        totpSecret_ = other.totpSecret_;
        onChanged();
      }
      if (!other.getLastUsedTotpSecret().isEmpty()) {
        lastUsedTotpSecret_ = other.lastUsedTotpSecret_;
        onChanged();
      }
      if (other.getIsTotpAppEnabled() != false) {
        setIsTotpAppEnabled(other.getIsTotpAppEnabled());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.appdirect.event.UserMFASettings parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.appdirect.event.UserMFASettings) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.appdirect.event.Resource resource_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.appdirect.event.Resource, com.appdirect.event.Resource.Builder, com.appdirect.event.ResourceOrBuilder> resourceBuilder_;
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public boolean hasResource() {
      return resourceBuilder_ != null || resource_ != null;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public com.appdirect.event.Resource getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? com.appdirect.event.Resource.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder setResource(com.appdirect.event.Resource value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        resourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder setResource(
        com.appdirect.event.Resource.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder mergeResource(com.appdirect.event.Resource value) {
      if (resourceBuilder_ == null) {
        if (resource_ != null) {
          resource_ =
            com.appdirect.event.Resource.newBuilder(resource_).mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        resourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public Builder clearResource() {
      if (resourceBuilder_ == null) {
        resource_ = null;
        onChanged();
      } else {
        resource_ = null;
        resourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public com.appdirect.event.Resource.Builder getResourceBuilder() {
      
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    public com.appdirect.event.ResourceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            com.appdirect.event.Resource.getDefaultInstance() : resource_;
      }
    }
    /**
     * <code>optional .com.appdirect.event.Resource resource = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.appdirect.event.Resource, com.appdirect.event.Resource.Builder, com.appdirect.event.ResourceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.appdirect.event.Resource, com.appdirect.event.Resource.Builder, com.appdirect.event.ResourceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private java.lang.Object pendingTotpSecret_ = "";
    /**
     * <code>optional string pendingTotpSecret = 2;</code>
     */
    public java.lang.String getPendingTotpSecret() {
      java.lang.Object ref = pendingTotpSecret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pendingTotpSecret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string pendingTotpSecret = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPendingTotpSecretBytes() {
      java.lang.Object ref = pendingTotpSecret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pendingTotpSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string pendingTotpSecret = 2;</code>
     */
    public Builder setPendingTotpSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pendingTotpSecret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string pendingTotpSecret = 2;</code>
     */
    public Builder clearPendingTotpSecret() {
      
      pendingTotpSecret_ = getDefaultInstance().getPendingTotpSecret();
      onChanged();
      return this;
    }
    /**
     * <code>optional string pendingTotpSecret = 2;</code>
     */
    public Builder setPendingTotpSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pendingTotpSecret_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object totpSecret_ = "";
    /**
     * <code>optional string totpSecret = 3;</code>
     */
    public java.lang.String getTotpSecret() {
      java.lang.Object ref = totpSecret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        totpSecret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string totpSecret = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTotpSecretBytes() {
      java.lang.Object ref = totpSecret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totpSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string totpSecret = 3;</code>
     */
    public Builder setTotpSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      totpSecret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string totpSecret = 3;</code>
     */
    public Builder clearTotpSecret() {
      
      totpSecret_ = getDefaultInstance().getTotpSecret();
      onChanged();
      return this;
    }
    /**
     * <code>optional string totpSecret = 3;</code>
     */
    public Builder setTotpSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      totpSecret_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastUsedTotpSecret_ = "";
    /**
     * <code>optional string lastUsedTotpSecret = 4;</code>
     */
    public java.lang.String getLastUsedTotpSecret() {
      java.lang.Object ref = lastUsedTotpSecret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastUsedTotpSecret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string lastUsedTotpSecret = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLastUsedTotpSecretBytes() {
      java.lang.Object ref = lastUsedTotpSecret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastUsedTotpSecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string lastUsedTotpSecret = 4;</code>
     */
    public Builder setLastUsedTotpSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastUsedTotpSecret_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastUsedTotpSecret = 4;</code>
     */
    public Builder clearLastUsedTotpSecret() {
      
      lastUsedTotpSecret_ = getDefaultInstance().getLastUsedTotpSecret();
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastUsedTotpSecret = 4;</code>
     */
    public Builder setLastUsedTotpSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastUsedTotpSecret_ = value;
      onChanged();
      return this;
    }

    private boolean isTotpAppEnabled_ ;
    /**
     * <code>optional bool isTotpAppEnabled = 5;</code>
     */
    public boolean getIsTotpAppEnabled() {
      return isTotpAppEnabled_;
    }
    /**
     * <code>optional bool isTotpAppEnabled = 5;</code>
     */
    public Builder setIsTotpAppEnabled(boolean value) {
      
      isTotpAppEnabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isTotpAppEnabled = 5;</code>
     */
    public Builder clearIsTotpAppEnabled() {
      
      isTotpAppEnabled_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.appdirect.event.UserMFASettings)
  }

  // @@protoc_insertion_point(class_scope:com.appdirect.event.UserMFASettings)
  private static final com.appdirect.event.UserMFASettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.appdirect.event.UserMFASettings();
  }

  public static com.appdirect.event.UserMFASettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserMFASettings>
      PARSER = new com.google.protobuf.AbstractParser<UserMFASettings>() {
    public UserMFASettings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserMFASettings(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserMFASettings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserMFASettings> getParserForType() {
    return PARSER;
  }

  public com.appdirect.event.UserMFASettings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

